version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'developer'
      POSTGRES_PASSWORD: 'supersecretpassword'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - '8090:8080'
    depends_on:
      - postgres
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend

volumes:
  postgres-data:
    name: postgres-data

networks:
  backend:
    name: backend-network
